#!/usr/bin/env bash

echo "#######################################################################"
echo "#                                                                     #"
echo "#   Bash script Automation (git command)                              #"
echo "#                                                                     #"
echo "#   commands to push your source code in your repository              #"
echo "#   (run: ./git)                                                      #"
echo "#                                                                     #"
echo "#######################################################################"

git add .

if [ -z "$GITCOMMIT" ]
then
        echo "commit is empty"
        echo "write some message:"
        read -r commit
        while [ -z "$commit" ]
        do
               echo "please write some message: "
               read -r commit
       done
       export GITCOMMIT="script git writting js - $commit"
fi

git commit -m "$GITCOMMIT"
git push

echo " "
echo "code success | https://dirkk.ci"
